#!/usr/bin/env python
import getopt
import os
import sys 
def show_help():
    print("Usage: trim -i input [-s 0:00] [-f finish] [-o output]")
    print("trim -h shows this menu again")

def main(argv):
    inp_file=""
    out_file=""
    t_start="0:00"
    t_finish=""
    command = ["ffmpeg"]


    opts, args = getopt.getopt(argv, "i:s:f:oh", ["--start=", "--finish="])
    for opt, val in opts:
        if opt == '-i':
            inp_file = val
        elif opt == '-o':
            out_file = val
        elif opt in ("-s", "--start"):
            t_start = val
        elif opt in ("-f", "--finish"):
            t_finish = val
        else:
            show_help()
            exit(0)
    
    if len(inp_file) > 0:
        command.append(f"-i '{inp_file}'")
    else:
        print("please give an input file with -i <video>")
        exit(1)

    command.append(f'-ss {t_start}')
    if len(t_finish) > 0:
        command.append(f'-to {t_finish}')
    if len(out_file) == 0:
        for fmt in [".mp4", ".mov", ".mkv", ".webm", ".3gp"]:
            if inp_file.lower().endswith(fmt):
                out_file = inp_file.split(fmt)[0] + "_trim" + fmt
    
    command.append(f"'{out_file}'")
    print(command)
    os.system(' '.join(command))

if __name__ == "__main__":
   main(sys.argv[1:])