#! /bin/sh
GREEN='\033[1;32m'
NORMAL='\033[0m'
echo -e "${GREEN}UPDATING SYSTEM PACKAGES${NORMAL}"
paru -Syu --combinedupgrade
echo -e "${GREEN}UPDATING FLATPAKS${NORMAL}"
flatpak update -y
echo -e "${GREEN}DONE!${NORMAL}"

